MODULE = "Erpnext Srilankan Localisation"

CUSTOM_FIELDS = {
	"Customer": [
		{
			"fieldname": "lk_section_tax_registration",
			"label": "Tax Registration",
			"fieldtype": "Section Break",
			"insert_after": "tax_tab",
			"module": MODULE,
		},
		{
			"fieldname": "lk_brc_no",
			"label": "BRC No",
			"fieldtype": "Data",
			"insert_after": "lk_section_tax_registration",
			"depends_on": "eval:doc.customer_type!='Individual'",
			"module": MODULE,
		},
		{
			"fieldname": "lk_tin_no",
			"label": "TIN Registration No",
			"fieldtype": "Data",
			"insert_after": "lk_brc_no",
			"depends_on": "eval:doc.customer_type!='Individual'",
			"module": MODULE,
		},
		{
			"fieldname": "lk_col_break_tax",
			"fieldtype": "Column Break",
			"insert_after": "lk_tin_no",
			"module": MODULE,
		},
		{
			"fieldname": "lk_is_vat_registered",
			"label": "VAT Registered",
			"fieldtype": "Check",
			"insert_after": "lk_col_break_tax",
			"default": "0",
			"module": MODULE,
		},
		{
			"fieldname": "lk_vat_no",
			"label": "VAT No",
			"fieldtype": "Data",
			"insert_after": "lk_is_vat_registered",
			"depends_on": "eval:doc.lk_is_vat_registered==1",
			"module": MODULE,
		},
		{
			"fieldname": "lk_vat_registration_certificate",
			"label": "VAT Registration Certificate",
			"fieldtype": "Attach",
			"insert_after": "lk_vat_no",
			"depends_on": "eval:doc.lk_is_vat_registered==1",
			"module": MODULE,
		},
	],
	"Supplier": [
		{
			"fieldname": "lk_section_tax_registration",
			"label": "Tax Registration",
			"fieldtype": "Section Break",
			"insert_after": "tax_tab",
			"module": MODULE,
		},
		{
			"fieldname": "lk_brc_no",
			"label": "BRC No",
			"fieldtype": "Data",
			"insert_after": "lk_section_tax_registration",
			"depends_on": "eval:doc.supplier_type!='Individual'",
			"module": MODULE,
		},
		{
			"fieldname": "lk_tin_no",
			"label": "TIN Registration No",
			"fieldtype": "Data",
			"insert_after": "lk_brc_no",
			"depends_on": "eval:doc.supplier_type!='Individual'",
			"module": MODULE,
		},
		{
			"fieldname": "lk_col_break_tax",
			"fieldtype": "Column Break",
			"insert_after": "lk_tin_no",
			"module": MODULE,
		},
		{
			"fieldname": "lk_is_vat_registered",
			"label": "VAT Registered",
			"fieldtype": "Check",
			"insert_after": "lk_col_break_tax",
			"default": "0",
			"module": MODULE,
		},
		{
			"fieldname": "lk_vat_no",
			"label": "VAT No",
			"fieldtype": "Data",
			"insert_after": "lk_is_vat_registered",
			"depends_on": "eval:doc.lk_is_vat_registered==1",
			"module": MODULE,
		},
		{
			"fieldname": "lk_vat_registration_certificate",
			"label": "VAT Registration Certificate",
			"fieldtype": "Attach",
			"insert_after": "lk_vat_no",
			"depends_on": "eval:doc.lk_is_vat_registered==1",
			"module": MODULE,
		},
	],
	"Company": [
		{
			"fieldname": "lk_section_tax_registration",
			"label": "Tax Registration",
			"fieldtype": "Section Break",
			"insert_after": "reporting_currency",
			"module": MODULE,
		},
		{
			"fieldname": "lk_brc_no",
			"label": "BRC No",
			"fieldtype": "Data",
			"insert_after": "lk_section_tax_registration",
			"module": MODULE,
		},
		{
			"fieldname": "lk_tin_no",
			"label": "TIN Registration No",
			"fieldtype": "Data",
			"insert_after": "lk_brc_no",
			"module": MODULE,
		},
		{
			"fieldname": "lk_col_break_tax",
			"fieldtype": "Column Break",
			"insert_after": "lk_tin_no",
			"module": MODULE,
		},
		{
			"fieldname": "lk_is_sscl_registered",
			"label": "SSCL Registered",
			"fieldtype": "Check",
			"insert_after": "lk_col_break_tax",
			"default": "0",
			"module": MODULE,
		},
		{
			"fieldname": "lk_sscl_no",
			"label": "SSCL Registration No",
			"fieldtype": "Data",
			"insert_after": "lk_is_sscl_registered",
			"depends_on": "eval:doc.lk_is_sscl_registered==1",
			"module": MODULE,
		},
		{
			"fieldname": "lk_sscl_business_category",
			"label": "SSCL Business Category",
			"fieldtype": "Select",
			"options": "\nImportation\nManufacturing\nGeneral Services\nRegistered Distributor\nOther Wholesale or Retail",
			"insert_after": "lk_sscl_no",
			"depends_on": "eval:doc.lk_is_sscl_registered==1",
			"description": "Determines the % of turnover liable for SSCL - see IRD guidance.",
			"module": MODULE,
		},
		{
			"fieldname": "lk_is_vat_registered",
			"label": "VAT Registered",
			"fieldtype": "Check",
			"insert_after": "lk_sscl_no",
			"default": "0",
			"module": MODULE,
		},
		{
			"fieldname": "lk_vat_no",
			"label": "VAT No",
			"fieldtype": "Data",
			"insert_after": "lk_is_vat_registered",
			"depends_on": "eval:doc.lk_is_vat_registered==1",
			"module": MODULE,
		},
		{
			"fieldname": "lk_vat_registration_certificate",
			"label": "VAT Registration Certificate",
			"fieldtype": "Attach",
			"insert_after": "lk_vat_no",
			"depends_on": "eval:doc.lk_is_vat_registered==1",
			"module": MODULE,
		},
	],
	"Sales Invoice": [
		{
			"fieldname": "lk_mode_of_payment",
			"label": "Mode of Payment",
			"fieldtype": "Link",
			"options": "Mode of Payment",
			"insert_after": "due_date",
			"module": MODULE,
		},
		{
			"fieldname": "lk_customer_tin_no",
			"label": "Customer TIN No",
			"fieldtype": "Data",
			"insert_after": "tax_id",
			"fetch_from": "customer.lk_tin_no",
			"read_only": 1,
			"module": MODULE,
		},
		{
			"fieldname": "lk_customer_vat_no",
			"label": "Customer VAT No",
			"fieldtype": "Data",
			"insert_after": "lk_customer_tin_no",
			"fetch_from": "customer.lk_vat_no",
			"read_only": 1,
			"module": MODULE,
		},
	],
	"Purchase Invoice": [
		{
			"fieldname": "lk_supplier_tin_no",
			"label": "Supplier TIN No",
			"fieldtype": "Data",
			"insert_after": "tax_id",
			"fetch_from": "supplier.lk_tin_no",
			"read_only": 1,
			"module": MODULE,
		},
		{
			"fieldname": "lk_supplier_vat_no",
			"label": "Supplier VAT No",
			"fieldtype": "Data",
			"insert_after": "lk_supplier_tin_no",
			"fetch_from": "supplier.lk_vat_no",
			"read_only": 1,
			"module": MODULE,
		},
	],
}
