name: tests

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate App
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON
        run: |
          python -m json.tool erpnext_srilankan_localisation/fixtures/chart_of_accounts/lk_standard_chart_of_accounts.json

      - name: Compile Python
        run: |
          python -m compileall erpnext_srilankan_localisation

  semgrep:
    runs-on: ubuntu-latest
    name: Semgrep Scan
    steps:
      - uses: actions/checkout@v4

      - name: Clone Semgrep rules
        run: |
          git clone https://github.com/frappe/semgrep-rules.git

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep scan --config semgrep-rules/rules --error